version: 2

models:
  - name: stg_addresses
    description: something
    columns:
      - name: address_id
        tests: 
          - unique
          - not_null
      - name: address
        tests: 
          - not_null
      - name: zipcode
        tests: 
          - not_null        
      - name: state
        tests:
          - not_null    
      - name: country
        tests: 
          - not_null
  - name: stg_users
    description: something
    columns:
      - name: user_id
        tests: 
          - unique
          - not_null
      - name: first_name
        tests: 
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - unique
          - not_null
      - name: phone_number
        tests: 
          - unique
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: updated_at
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null
  - name: stg_promos
    description: something
    columns:
      - name: promo_id
        tests: 
          - unique
          - not_null
      - name: discount
        tests: 
          - not_null
      - name: status
        tests: 
          - not_null        
  - name: stg_products
    description: something
    columns:
      - name: product_id
        tests: 
          - unique
          - not_null
      - name: name
        tests: 
          - not_null
      - name: price
        tests: 
          - not_null        
      - name: inventory
        tests:
          - not_null    
  - name: stg_orders
    description: something
    columns:
      - name: order_id
        tests: 
          - unique
          - not_null
      - name: user_id
        tests: 
          - not_null
      - name: promo_id
        tests: 
      - name: address_id
        tests:
          - not_null    
      - name: created_at
        tests: 
          - not_null
      - name: order_cost
        tests: 
          - not_null
      - name: tracking_id
        tests: 
          - unique
          - not_null
      - name: shipping_service
        tests: 
          - not_null
      - name: estimated_delivery_at
        tests: 
          - not_null
      - name: delivered_at
        tests: 
      - name: status
        tests: 
          - not_null
  - name: stg_order_items
    description: something
    columns:
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null
      - name: quantity
        tests: 
          - not_null
  - name: stg_events
    description: something
    columns:
      - name: event_id
        tests: 
          - unique
          - not_null
      - name: session_id
        tests: 
          - not_null
      - name: user_id
        tests: 
          - not_null
      - name: page_url
        tests:
          - not_null   
      - name: created_at
        tests: 
          - not_null
      - name: event_type
        tests: 
          - not_null
      - name: order_id
        tests:
          - not_null  
      - name: product_id
        tests:
          - not_null  