version: 2

models:
  - name: stg_addresses
    columns:
      - name: address_id
        tests: 
          - unique
          - not_null
      - name: address
        tests: 
          - not_null
      - name: zipcode
        tests: 
          - not_null        
      - name: state
        tests:
          - not_null    
      - name: country
        tests: 
          - not_null
  - name: stg_users
    columns:
      - name: user_id
        tests: 
          - unique
          - not_null
      - name: first_name
        tests: 
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - unique
          - not_null
      - name: phone_number
        tests: 
          - unique
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: updated_at
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null
          - relationships:
              to: ref('adress')
              field: address_id
  - name: stg_promos
    columns:
      - name: promo_id
        tests: 
          - unique
          - not_null
      - name: discount
        tests: 
          - not_null
          - positive_value
      - name: status
        tests: 
          - not_null        
  - name: stg_products
    columns:
      - name: product_id
        tests: 
          - unique
          - not_null
      - name: name
        tests: 
          - not_null
      - name: price
        tests: 
          - not_null        
      - name: inventory
        tests:
          - not_null    
  - name: stg_orders
    columns:
      - name: order_id
        tests: 
          - unique
          - not_null
      - name: user_id
        tests: 
          - not_null
          - relationships: 
              to: ref('users')
              field: user_id
      - name: promo_id
        tests: 
          - relationships: 
              to: ref('promos')
              field: promo_id
      - name: address_id
        tests:
          - not_null   
          - relationships:
              to: ref('addresses')
              field: address_id
      - name: created_at
        tests: 
          - not_null
      - name: order_cost
        tests: 
          - not_null
      - name: tracking_id
        tests: 
          - unique
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status
        tests: 
          - not_null
  - name: stg_order_items
    columns:
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null
          - relationships: 
              to: ref('products')
              field: product_id
      - name: quantity
        tests: 
          - not_null
  - name: stg_events
    columns:
      - name: event_id
        tests: 
          - unique
          - not_null
      - name: session_id
        tests: 
          - not_null
      - name: user_id
        tests: 
          - not_null
          - relationships:
              to: ref('users')
              field: user_id
      - name: page_url
        tests:
          - not_null   
      - name: created_at
        tests: 
          - not_null
      - name: event_type
        tests: 
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('orders')
              field: order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('products')
              field: product_id